#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-gitlab-runner ]; then

	CONFIG_DIR="/etc/gitlab-runner"
	CONFIG_FILE=${CONFIG_FILE:-$CONFIG_DIR/config.toml}
	HOME_DIR="/home/gitlab-runner"

	## Configure CA Certificates
	# custom certificate authority path
	CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-$CONFIG_DIR/certs/ca.crt}
	LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

	update_ca() {
	  echo "Updating CA certificates..."
	  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
	  update-ca-certificates --fresh >/dev/null
	}

	if [ -f "${CA_CERTIFICATES_PATH}" ]; then
	  # update the ca if the custom ca is different than the current
	  cmp -s "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
	fi

    ## Generate SSH Deploy Keys
    chown -R gitlab-runner:root ${HOME_DIR}
    chmod -R 700 ${HOME_DIR}
    sudo -HEu gitlab-runner mkdir -p ${HOME_DIR}/.ssh/

	  if [[ ! -e ${HOME_DIR}/.ssh/id_rsa || ! -e ${HOME_DIR}/.ssh/id_rsa.pub ]]; then
	    echo "Generating SSH deploy keys..."
	    rm -rf ${HOME_DIR}/.ssh/id_rsa ${HOME_DIR}/.ssh/id_rsa.pub
	    sudo -HEu gitlab-runner ssh-keygen -t rsa -N "" -f ${HOME_DIR}/.ssh/id_rsa

	    echo ""
	    echo -n "Your SSH deploy key is: "
	    cat ${HOME_DIR}/.ssh/id_rsa.pub
	    echo ""
	  fi

	  chmod 600 ${HOME_DIR}/.ssh/id_rsa ${HOME_DIR}/.ssh/id_rsa.pub
	  chmod 700 ${HOME_DIR}/.ssh
      chown -R gitlab-runner:root ${HOME_DIR}/.ssh/

    ## Configure Runner
	  chown -R gitlab-runner:root ${CONFIG_DIR}
      	 if [[ ! -f ${CONFIG_DIR}/config.toml ]]; then
		    if [[ -n ${CI_SERVER_URL} && -n ${RUNNER_TOKEN} && -n ${RUNNER_DESCRIPTION} && -n ${RUNNER_EXECUTOR} ]]; then
		       if [ ${RUNNER_EXECUTOR} = "docker" ];  then    
		       	    EXECUTOR_DOCKER_IMAGE=${EXECUTOR_DOCKER_IMAGE:-docker-git}
		        	sudo -HEu gitlab-runner gitlab-runner register --config $CONFIG_DIR/config.toml -n -u "${CI_SERVER_URL}" -r "${RUNNER_TOKEN}" --name "${RUNNER_DESCRIPTION}" --executor "${RUNNER_EXECUTOR}" --docker-volumes /var/run/docker.sock:/var/run/docker.sock --docker-image "${EXECUTOR_DOCKER_IMAGE}"
		        else
            	    sudo -HEu gitlab-runner gitlab-runner register --config ${CONFIG_DIR}/config.toml -n -u "${CI_SERVER_URL}" -r "${RUNNER_TOKEN}" --name "${RUNNER_DESCRIPTION}" --executor "${RUNNER_EXECUTOR}"
		        fi
		    fi
		 fi

    mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/10-gitlab-runner
fi

echo ''
echo '** Starting Gitlab Runner'
exec gitlab-ci-multi-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner

